# Generated by Django 2.2.3 on 2019-10-08 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_file_required', models.BooleanField()),
                ('imo_field', models.BooleanField(default=False)),
                ('spec_document', models.CharField(max_length=128)),
                ('media_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('metadata', models.TextField(blank=True, max_length=8192)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.EntityType')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='noname', max_length=1024)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('metadata', models.TextField(max_length=8192)),
                ('file_data', models.FileField(blank=True, upload_to='')),
                ('spec_version', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True, max_length=4096)),
                ('dependencies', models.ManyToManyField(blank=True, to='browser.DataFile')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Entity')),
            ],
        ),
    ]
